### ISSUE TITLE
Bastion Node - hostname update

### ISSUE THREAD

**Issue by egrol** [IBM-ICP4D/cloud-pak-ocp-4#16]
Hi Team,

Could I request a modification to the code base to not update the hostname of the bastion node as part of the UPI deployment process. I've realised after I have selected the OVA/UPI deployment process and set the managed_load_balancer option as true that the bastions hostname changes from what I had original set it to something else, for example: (The value is being appended with the cluster name)

Original node name:
bastion01.domain.ml

Modified node name:
bastion01.cluster01.domain.ml

This causes issues with my DNS name resolution within the environment especially if I have already pre-set my hostname for my bastion node.

Regards,

Erol

**Comment by fketelaars** [comment]
@egrol : Full agreement on this change, the bastion is essentially not part of the cluster. I have created an additional property in the inventory file to set the host name of the bastion. Default is False.
