### ISSUE TITLE
[offline registry instructions] New docker download restrictions

### ISSUE THREAD

**Issue by lrutland** [IBM-ICP4D/cloud-pak-ocp-4#4]
From beginning of November docker applied limits to the number of anonymous / unauthenticated pulls so may encounter following when trying to pull registry image:
```
# podman pull docker.io/library/registry:2
Trying to pull docker.io/library/registry:2...
  toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
Error: unable to pull docker.io/library/registry:2: Error initializing source docker://registry:2: Error reading manifest 2 in docker.io/library/registry: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

A free docker account can be created which would work around this.  [podman login docker.io]
Alternatively the image may be found in quay.io but location would need to be updated.  The user used to register with Redhat for subscription-manager should work with quay.io

**Comment by fketelaars** [comment]
I have not found the rate limiting to be an issue for individual containers. Not having to login is preferred I think so will not implement.
